# Generated by Django 3.2.6 on 2021-08-23 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slivki_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('msg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.TextField(max_length=100)),
                ('msg_text', models.TextField(max_length=4000)),
                ('photo_1', models.TextField(max_length=1000)),
                ('photo_2', models.TextField(max_length=1000)),
                ('photo_3', models.TextField(max_length=1000)),
                ('payment', models.IntegerField()),
                ('exp_date', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slivki_bot.users')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
    ]
