# Generated by Django 3.2.6 on 2021-08-24 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slivki_bot', '0004_alter_messages_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slivki_bot.users'),
        ),
    ]
