# Generated by Django 3.2.6 on 2021-08-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slivki_bot', '0005_alter_messages_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='comment',
            field=models.CharField(default='комментарий', max_length=4000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='exp_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='messages',
            name='msg_text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='photo_1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='photo_2',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='photo_3',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='user_name',
            field=models.CharField(max_length=100),
        ),
    ]
