# Generated by Django 3.2.6 on 2021-08-24 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slivki_bot', '0007_auto_20210824_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='user_id_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_id_id',
            new_name='user_id',
        ),
    ]
