# Generated by Django 3.2.6 on 2021-08-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slivki_bot', '0008_auto_20210824_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='msg_text',
            field=models.TextField(max_length=4000),
        ),
    ]
